//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::label::Entity as Label;
pub use super::task::Entity as Task;
pub use super::task_label::Entity as TaskLabel;
pub use super::user::Entity as User;
pub use super::user_profile::Entity as UserProfile;
